name: healthwire
description: Un super projet Flutter

# ✅ Ajoute ceci pour définir la version minimale requise de Dart
environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Autres dépendances ici...

flutter:
  assets:
    - assets/doctor.png
    - assets/patient.png
